config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
  }
  resources :chatrooms
  resources :users
  resources :notes
  root 'home#top'
  post '/' => 'home#mystudentyear'
  get '/about' => 'home#about'
  get '/mytop' => 'home#mytop'
  post '/mytop'=> 'home#mysubject'
  post '/like/:note_id' => 'likes#like', as:'like'
  delete '/unlike/:note_id' => 'likes#unlike', as:'unlike'
  post '/favorite/:chatroom_id' => 'favorites#favorite', as:'favorite'
  delete '/unfavorite/:chatroom_id' => 'favorites#unfavorite', as:'unfavorite'
  post '/friendship/:user_id' => 'friendships#submit', as:'submit'
  
  

end

app/models/chatroom.rb
class Chatroom < ActiveRecord::Base
    has_many :notes
    has_many :favorites, dependent: :destroy
    validates :title, presence: true
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
    belongs_to :user
    belongs_to :chatroom
end

app/models/friend.rb
class Friend < ActiveRecord::Base
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
    belongs_to :from_user, class_name: 'User', foreign_key: 'from_user_id'
    belongs_to :to_user, class_name: 'User', foreign_key: 'to_user_id'
end

app/models/like.rb
class Like < ActiveRecord::Base
    belongs_to :user
    belongs_to :note
end

app/models/note.rb
class Note < ActiveRecord::Base
    belongs_to :user
    belongs_to :chatroom
    has_many :likes, dependent: :destroy
    validates :content, presence: true
    validates :user_id, presence: true
end

app/models/prv_chatroom.rb
class PrvChatroom < ActiveRecord::Base
end

app/models/prv_note.rb
class PrvNote < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_many :notes
    has_many :likes, dependent: :destroy
    has_many :like_notes, through: :likes, source: :note
    has_many :favorites, dependent: :destroy
    has_many :favorite_chatrooms, through: :favorites, source: :chatroom
    has_many :friendships_from_user, class_name: 'Friensdhip', foreign_key: 'from_user_id', dependent: :delete_all
    has_many :friendships_to_user, class_name: 'Friedship', foreign_key: 'to_user_id', dependent: :delete_all
    has_many :friendships_of_from_user, through: :friendships_from_userr, source: 'to_user'
    has_many :friendships_of_to_user, through: :friendships_to_user, source: 'from_user'
    validates :name, presence: true 
    validates :email, presence: true, uniqueness: true
    validates :studentType, presence: true
    
    
    def set_image(file)
        if !file.nil?
            file_name = file.original_filename

            File.open("public/user_images/#{file_name}", 'wb'){|f| f.write(file.read)}
        end
        
        self.image = file_name

    end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :set_chatroom, only: [:show, :edit, :update, :destroy]

  # GET /chatrooms
  # GET /chatrooms.json
  def index
    @chatrooms = Chatroom.all
  end

  # GET /chatrooms/1
  # GET /chatrooms/1.json
  def show
    @note = Note.new
    Note.all.order(created_at: :asc)
    @notes = Note.where(chatroom_id: @chatroom.id)
    $chatroom_id = params[:id]
  end

  # GET /chatrooms/new
  def new
    @chatroom = Chatroom.new
  end

  # POST /chatrooms
  # POST /chatrooms.json
  def create
    @chatroom = Chatroom.new(chatroom_params)
    @chatroom.studentYear = $studentyear
    @chatroom.subject = $subject

    respond_to do |format|
      if @chatroom.save
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully created.' }
        format.json { render :show, status: :created, location: @chatroom }
      else
        format.html { render :new }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chatrooms/1
  # PATCH/PUT /chatrooms/1.json
  def update
    respond_to do |format|
      if @chatroom.update(chatroom_params)
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @chatroom }
      else
        format.html { render :edit }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chatrooms/1
  # DELETE /chatrooms/1.json
  def destroy
    @chatroom.destroy
    respond_to do |format|
      format.html { redirect_to chatrooms_url, notice: 'Chatroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chatroom
      @chatroom = Chatroom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chatroom_params
      params.require(:chatroom).permit(:title)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def top
    if user_signed_in? && !(current_user.studentType == "その他")
      $studentyear = current_user.studentYear
      redirect_to mytop_path
    end
    @chatrooms = Chatroom.order(:updated_at)
  end
  
  def about
  end
  
  def mytop
    unless defined? $studentyear
      redirect_to root_path
    end
    @chatrooms = Chatroom.order("updated_at")
  end
  
  def mystudentyear
    #topページ下部のボタンからのリンク接続
    if params[:studentyear].present? then
      $studentyear = params[:studentyear].to_i
      redirect_to mytop_path
    elsif params[:subject].present? then
      subyear = params[:subject].partition(/[3-6]/)
      $subject = subyear[0]
      $studentyear = subyear[1].to_i
      redirect_to chatrooms_path
    elsif params[:chatroom].present? then
      subyearid = params[:chatroom].partition(/[3-6]/)
      $subject = subyearid[0]
      $studentyear = subyearid[1].to_i
      redirect_to chatroom_path(subyearid[2].to_i)
    end
      
  end
  
  def mysubject
    #topページ下部のボタンからのリンク接続
    if params[:subject].present? then
      $subject = params[:subject]
      redirect_to chatrooms_path
    elsif params[:chatroom].present? then
      subyearid = params[:chatroom].partition(/[0-9]*$/)
      $subject = subyearid[0]
      redirect_to chatroom_path(subyearid[1].to_i)
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def like
        @note = Note.find(params[:note_id])
        like = current_user.likes.build(note_id: @note.id)
        like.save
    end
    
    def unlike
        @note = Note.find(params[:note_id])
        like = current_user.likes.find_by(note_id: @note.id)
        like.destroy
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/prvchatrooms_helper.rb
module PrvchatroomsHelper
end

app/helpers/prvnotes_helper.rb
module PrvnotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chatrooms/_form.html.erb
<%= form_for(@chatroom) do |f| %>
  <% if @chatroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chatroom.errors.count, "error") %> prohibited this chatroom from being saved:</h2>

      <ul>
      <% @chatroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chatrooms/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      

      <h1>Editing Chatroom</h1>
      
      <%= render 'form' %>
      
      <%= link_to 'Show', @chatroom %> |
      <%= link_to 'Back', chatrooms_path %>
    </div>
  </div>
</div>

app/views/chatrooms/index.html.erb
<div class="container chatrooms">
  <div class="row">
    <div class="col-xs-12">
      

      <p id="notice"><%= notice %></p>
      
      <h1>部屋を選ぶ</h1>
      <nav class="navbar navbar-none" style="margin-bottom: 0;">
        <%= form_tag root_path do %>
        <% year_list = [6, 5, 4, 3] %>
        <% year_class = { 3=>'btn btn-xs btn-primary', 4=>'btn btn-xs btn-warning', 5=>'btn btn-xs btn-info', 6=>'btn btn-xs btn-success' } %>
          <div class="">
            <ul class="">
              <% (1..4).each do %>
              <% if year_list[-1] == $studentyear %>
                <li class="navbar-brand lighten-btn">
              <% else %>
                <li class="lighten-btn">
              <% end %>
                  <%= button_tag year_list[-1].to_s + "年生", :class => year_class.shift[1], :name => 'studentyear', :value => year_list.pop, :style => 'color: #fff;' %>
                </li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </nav>
      
      <!-- 教科を選択する -->
      <nav class="navbar navbar-none">
        <%= form_tag mytop_path do %>
        <% subject_list = %w(社会 理科 算数 国語) %>
        <% subject_class = {'国語'=>'btn btn-danger', '算数'=>'btn btn-info', '理科'=>'btn btn-success', '社会'=>'btn btn-warning'} %>
          <div class="">
            <ul class="">
              <% (1..4).each do %>
              <% if subject_list[-1] == $subject %>
                <li class="navbar-brand">
              <% else %>
                <li>
              <% end %>
                  <%= button_tag subject_list[-1], :class => subject_class.shift[1], :name => 'subject', :value => subject_list.pop %>
                </li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </nav>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
  
      
      <!-- チャットルームの作成 -->
      <br>
      <% if user_signed_in? %>
      <%= link_to '新しくチャットルームを作る', new_chatroom_path %>
      <% end %>

  
    </div>
  </div>
      <!-- チャットルームの表示 -->
  <div class="row new-chat">
    <div class="col-xs-12">
      <article>
        <h5>チャットルームログ</h5>
        <div class="">
          <% @chatrooms.each do |chatroom| %>
            <% if chatroom.studentYear == $studentyear && chatroom.subject == $subject %>
              <div class="btn-group">
                <% subject_class = {'国語'=>'btn btn-danger btn-xs', '算数'=>'btn btn-info btn-xs', '理科'=>'btn btn-success btn-xs', '社会'=>'btn btn-warning btn-xs'} %>
                <% year_class = { 3=>'btn btn-xs btn-primary', 4=>'btn btn-xs btn-warning', 5=>'btn btn-xs btn-info', 6=>'btn btn-xs btn-success' } %>
                <%= button_tag chatroom.subject, :name => 'subject', :class => subject_class[chatroom.subject], :type => 'submit', :disabled => 'disable' %>
                <%= button_tag chatroom.studentYear.to_s + '年', :name => 'studentyear', :class => year_class[chatroom.studentYear], :type => 'submit', :disabled => 'disable' %>
                <%= link_to chatroom.title, chatroom, :class => 'btn btn-default btn-xs' %>
              </div>
              <div></div>
            <% end %>
          <% end %>
        </div>
      </article>
    </div>
  </div>
</div>

<!--
左に移動するタイプ
      <nav class="navbar navbar-none" style="margin-bottom: 0;">
        <%= form_tag root_path do %>
        <% year_list = [6, 5, 4, 3] %>
        <% year_class = { 6=>'btn btn-xs btn-success', 5=>'btn btn-xs btn-info', 4=>'btn btn-xs btn-warning', 3=>'btn btn-xs btn-primary' } %>
          <div class="">
            <ul class="">
              <li class="navbar-brand"><%= button_tag $studentyear.to_s + "年生", :class => year_class[$studentyear], :name => 'studentyear', :value => $studentyear %></li>
              <% year_list.delete $studentyear%>
              <% year_class.delete $studentyear%>
              <% (1..3).each do %>
                <li><%= button_tag year_list[-1].to_s + "年生", :class => year_class.shift[1], :name => 'studentyear', :value => year_list.pop %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </nav>

      <nav class="navbar navbar-none">
        <%= form_tag mytop_path do %>
        <% subject_list = %w(社会 理科 算数 国語) %>
        <% subject_class = {'国語'=>'btn btn-danger', '算数'=>'btn btn-info', '理科'=>'btn btn-success', '社会'=>'btn btn-warning'} %>
          <div class="">
            <ul class="">
              <li class="navbar-brand"><%= button_tag $subject, :class => subject_class[$subject], :name => 'subject', :value => $subject %></li>
              <% subject_list.delete $subject%>
              <% subject_class.delete $subject%>
              <% (1..3).each do %>
                <li><%= button_tag subject_list[-1], :class => subject_class.shift[1], :name => 'subject', :value => subject_list.pop %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </nav>
      -->

app/views/chatrooms/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      
      <h1>New Chatroom</h1>
      
      <%= render 'form' %>
      
      <%= link_to 'Back', chatrooms_path %>

    </div>
  </div>
</div>

app/views/chatrooms/show.html.erb
<% I18n.with_options :scope => [:activerecord, :attributes, :chatroom] do |l| %>
<div class="container chatroom">
  <div class="row">
    <div class="col-xs-12">
      

      <p id="notice"><%= notice %></p>
      
      
      <!-- チャットルームのタイトルの表示 -->
      <!-- チャットルームにいいねする -->
      <p>
        <%= l.t :title %>
        <%= @chatroom.title %>
        <span class="fav-right">
          <% if user_signed_in? %>
          <div id="favorite-link-<%= @chatroom.id %>"> <!-- favorite-linkはAjaxで使うから残しといて タグ名は変えていいよ(div→spanとか) -->
            <%= render "favorites/favorite_links", chatroom: @chatroom %>
          </div>
          <% end %>
        </span>
      </p>

      <p>
        <%= l.t :subject %>
        <%= @chatroom.subject %>
      </p>

      <p>
        <%= l.t :studentYear %>
        <%= @chatroom.studentYear %>年
      </p>
      
      
      <!-- コメントの表示 -->
      <div class="">
        <% @notes.each do |note| %>
          <div class="">
            <% if user_signed_in? %>
              <% if current_user.id == note.user.id %>
                <%= note.user.name %>
                <%= note.user.studentType %>
                <% if note.user.studentType != "その他" %>
                  <%= note.user.studentYear.to_s + "年生" %>
                <% end %>
                <span class="right">
                  <%= link_to '消去', note, method: :delete, data: { confirm: '本当に消しても大丈夫ですか？' } %>
                </span>
                <div class="chat chat-right">
                  <%= note.content %>
                </div>
              <% else %>
                <span id="like-link-<%= note.id %>"><!-- like-linkはAjaxで使うから残しといて タグ名は変えていいよ(div→spanとか) -->
                  <%= render "likes/like_links", note: note %>
                </span>
                <span>
                  <a href="#rep" onclick="showComment('<%= note.content %>')"><!--コメント--></a>
                </span>
                <span class="right">
                  <%= note.user.studentType %>
                  <% if note.user.studentType != "その他" %>
                    <%= note.user.studentYear.to_s + "年生" %>
                  <% end %>
                  <%= note.user.name %>
                </span>
                <div class="chat chat-right">
                  <%= note.content %>
                </div>
              <% end %>
            <% else %>
              <span>　</span>
              <span class="right">
                <%= note.user.studentType %>
                <% if note.user.studentType != "その他" %>
                  <%= note.user.studentYear %>
                <% end %>
                <%= note.user.name %>
              </span>
              <div class="chat chat-right">
                <%= note.content %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
      <!-- コメントの作成 -->
      <div class="">
        <% if user_signed_in? %>
          <%= render 'notes/form' %>
        <% end %>
      </div>
      <%= link_to image_tag("back.png", :size => "35x35", :alt => "アイコン", :style => "position: fixed; left: 3%; bottom: 5%;"), chatrooms_path %>
    </div>
  </div>
</div>
<% end %>