config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
  }
  resources :chatrooms
  resources :users
  resources :notes
  root 'home#top'
  post '/' => 'home#mystudentyear'
  get '/about' => 'home#about'
  get '/mytop' => 'home#mytop'
  post '/mytop'=> 'home#mysubject'
  post '/like/:note_id' => 'likes#like', as:'like'
  delete '/unlike/:note_id' => 'likes#unlike', as:'unlike'
  post '/favorite/:chatroom_id' => 'favorites#favorite', as:'favorite'
  delete '/unfavorite/:chatroom_id' => 'favorites#unfavorite', as:'unfavorite'
  post '/friendship/:user_id' => 'friendships#submit', as:'submit'
  
  

end

app/models/chatroom.rb
class Chatroom < ActiveRecord::Base
    has_many :notes
    has_many :favorites, dependent: :destroy
    validates :title, presence: true
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
    belongs_to :user
    belongs_to :chatroom
end

app/models/friend.rb
class Friend < ActiveRecord::Base
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
    belongs_to :from_user, class_name: 'User', foreign_key: 'from_user_id'
    belongs_to :to_user, class_name: 'User', foreign_key: 'to_user_id'
end

app/models/like.rb
class Like < ActiveRecord::Base
    belongs_to :user
    belongs_to :note
end

app/models/note.rb
class Note < ActiveRecord::Base
    belongs_to :user
    belongs_to :chatroom
    has_many :likes, dependent: :destroy
    validates :content, presence: true
    validates :user_id, presence: true
end

app/models/prv_chatroom.rb
class PrvChatroom < ActiveRecord::Base
end

app/models/prv_note.rb
class PrvNote < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_many :notes
    has_many :likes, dependent: :destroy
    has_many :like_notes, through: :likes, source: :note
    has_many :favorites, dependent: :destroy
    has_many :favorite_chatrooms, through: :favorites, source: :chatroom
    has_many :friendships_from_user, class_name: 'Friensdhip', foreign_key: 'from_user_id', dependent: :delete_all
    has_many :friendships_to_user, class_name: 'Friedship', foreign_key: 'to_user_id', dependent: :delete_all
    has_many :friendships_of_from_user, through: :friendships_from_userr, source: 'to_user'
    has_many :friendships_of_to_user, through: :friendships_to_user, source: 'from_user'
    validates :name, presence: true 
    validates :email, presence: true, uniqueness: true
    validates :studentType, presence: true
    
    
    def set_image(file)
        if !file.nil?
            file_name = file.original_filename

            File.open("public/user_images/#{file_name}", 'wb'){|f| f.write(file.read)}
        end
        
        self.image = file_name

    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def top
    if user_signed_in? && !(current_user.studentType == "その他")
      $studentyear = current_user.studentYear
      redirect_to mytop_path
    end
    @chatrooms = Chatroom.order(:updated_at)
  end
  
  def about
  end
  
  def mytop
    unless defined? $studentyear
      redirect_to root_path
    end
    @chatrooms = Chatroom.order("updated_at")
  end
  
  def mystudentyear
    #topページ下部のボタンからのリンク接続
    if params[:studentyear].present? then
      $studentyear = params[:studentyear].to_i
      redirect_to mytop_path
    elsif params[:subject].present? then
      subyear = params[:subject].partition(/[3-6]/)
      $subject = subyear[0]
      $studentyear = subyear[1].to_i
      redirect_to chatrooms_path
    elsif params[:chatroom].present? then
      subyearid = params[:chatroom].partition(/[3-6]/)
      $subject = subyearid[0]
      $studentyear = subyearid[1].to_i
      redirect_to chatroom_path(subyearid[2].to_i)
    end
      
  end
  
  def mysubject
    #topページ下部のボタンからのリンク接続
    if params[:subject].present? then
      $subject = params[:subject]
      redirect_to chatrooms_path
    elsif params[:chatroom].present? then
      subyearid = params[:chatroom].partition(/[0-9]*$/)
      $subject = subyearid[0]
      redirect_to chatroom_path(subyearid[1].to_i)
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def like
        @note = Note.find(params[:note_id])
        like = current_user.likes.build(note_id: @note.id)
        like.save
    end
    
    def unlike
        @note = Note.find(params[:note_id])
        like = current_user.likes.find_by(note_id: @note.id)
        like.destroy
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes.json

  # GET /notes/1.json

  def new
    @note = Note.new
  end


  # POST /notes.json
  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    @note.chatroom_id = $chatroom_id
    @chatroom = Chatroom.find_by(id: @note.chatroom_id)
    @chatroom.updated_at = Time.now
    respond_to do |format|
      if @note.save
        @chatroom.save
        format.html { redirect_to chatroom_path($chatroom_id), notice: 'コメントは保存されました。' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1.json
  def destroy
    #if !user_signed_in? || current_user.id != @user.id
    #  redirect_to root_path
    #end
    
    @note.destroy
    respond_to do |format|
      format.html { redirect_to chatroom_path($chatroom_id), notice: 'コメントはさくじょされました。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/prvchatrooms_helper.rb
module PrvchatroomsHelper
end

app/helpers/prvnotes_helper.rb
module PrvnotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/likes/_like_links.html.erb
  <% if current_user.likes.find_by(note_id: note.id) %>
    <%= link_to 'いいね！を取り消す', unlike_path(note.id), method: :delete, remote: true %>
  <% else %>
    <%= link_to 'いいね！', like_path(note.id), method: :post, remote: true %>
  <% end %>

app/views/likes/like.js.erb
$('#like-link-<%= @note.id %>').html('<%= escape_javascript(render("likes/like_links", note: @note)) %>');

app/views/likes/unlike.js.erb
$('#like-link-<%= @note.id %>').html('<%= escape_javascript(render("likes/like_links", note: @note)) %>');

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, :class => 'form-control' %>
  </div>
  <div id="rep" class="reply" style="display: none;">
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
 

app/views/notes/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      

      <p id="notice"><%= notice %></p>
      
      <h1>Listing Notes</h1>
      
      <table>
        <thead>
          <tr>
            <th>Content</th>
            <th>Studenttype</th>
            <th>Subject</th>
            <th colspan="3"></th>
          </tr>
        </thead>
      
        <tbody>
          <% @notes.each do |note| %>
            <tr>
              <td><%= note.content %></td>
              <td><%= note.studentType %></td>
              <td><%= note.subject %></td>
              <td><%= link_to 'Show', note %></td>
              <td><%= link_to 'Edit', edit_note_path(note) %></td>
              <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      
      <br>
      
      <%= link_to 'New Note', new_note_path %>

    </div>
  </div>
</div>

app/views/notes/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      
      <p id="notice"><%= notice %></p>
      
      <p>
        <strong>Content:</strong>
        <%= @note.content %>
      </p>
      
      <p>
        <strong>Studenttype:</strong>
        <%= @note.studentType %>
      </p>
      
      <p>
        <strong>Subject:</strong>
        <%= @note.subject %>
      </p>
      
      <p>
        <strong>name:</strong>
        <%= @note.user.name %>
      </p>
      
      
      <% if user_signed_in? && current_user.id == @note.user.id %>
      <%= link_to 'Edit', edit_note_path(@note) %> 
      <% end %>
      <%= link_to 'Back', notes_path %>

    </div>
  </div>
</div>