config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
  }
  resources :chatrooms
  resources :users
  resources :notes
  root 'home#top'
  post '/' => 'home#mystudentyear'
  get '/about' => 'home#about'
  get '/mytop' => 'home#mytop'
  post '/mytop'=> 'home#mysubject'
  post '/like/:note_id' => 'likes#like', as:'like'
  delete '/unlike/:note_id' => 'likes#unlike', as:'unlike'
  post '/favorite/:chatroom_id' => 'favorites#favorite', as:'favorite'
  delete '/unfavorite/:chatroom_id' => 'favorites#unfavorite', as:'unfavorite'
  post '/friendship/:user_id' => 'friendships#submit', as:'submit'
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_many :notes
    has_many :likes, dependent: :destroy
    has_many :like_notes, through: :likes, source: :note
    has_many :favorites, dependent: :destroy
    has_many :favorite_chatrooms, through: :favorites, source: :chatroom
    has_many :friendships_from_user, class_name: 'Friensdhip', foreign_key: 'from_user_id', dependent: :delete_all
    has_many :friendships_to_user, class_name: 'Friedship', foreign_key: 'to_user_id', dependent: :delete_all
    has_many :friendships_of_from_user, through: :friendships_from_userr, source: 'to_user'
    has_many :friendships_of_to_user, through: :friendships_to_user, source: 'from_user'
    validates :name, presence: true 
    validates :email, presence: true, uniqueness: true
    validates :studentType, presence: true
    
    
    def set_image(file)
        if !file.nil?
            file_name = file.original_filename

            File.open("public/user_images/#{file_name}", 'wb'){|f| f.write(file.read)}
        end
        
        self.image = file_name

    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    build_resource({})
    respond_with self.resource
  end

  # POST /resource
  def create
    build_resource(sign_up_params)
 
    if resource.save
      yield resource if block_given?
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_flashing_format?
        sign_up(resource_name, resource)
        respond_with resource, :location => after_sign_up_path_for(resource)
        
        
        
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
        expire_data_after_sign_in!
        respond_with resource, :location => after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      respond_with resource
    end
  end
    

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  def build_resource(hash=nil)
    if params['studentYear'].to_i <= 6 && params['studentYear'].to_i >= 3
      hash['studentYear'] = params['studentYear'].to_i
      hash['studentType'] = "小学生"
    else
      hash['studentType'] = "その他"
    end
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1.json
  def show
    @notes = @user.like_notes
    @chatrooms = @user.favorite_chatrooms
  end

  def edit
    if !user_signed_in? || current_user.id != @user.id
      redirect_to root_path
    end
  end
  # PATCH/PUT /users/1.json
  def update
    file = params[:user][:image]
    @user.set_image(file)
    
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_path(@user.id), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1.json
  def destroy
    if !user_signed_in?  #current_user.id != @user.id
      redirect_to root_path
    end
    
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'ユーザはさくじょされました。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :studentType, :studentYear)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :studentType %><br>
    <%= f.select :studentType, {"小学生" => "小学", "その他" => "その他"} %>
  </div>
  <div class="field">
    <%= f.label :studentYear %><br>
    <%= f.number_field :studentYear, min: 3, max: 6, step: 1 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      

      <h1>Editing User</h1>
      
      <%= render 'form' %>
      
      <%= link_to 'Show', @user %> |
      <%= link_to 'Back', users_path %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      
      
      <p id="notice"><%= notice %></p>
      
      <h1>Listing Users</h1>
      
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th colspan="3"></th>
          </tr>
        </thead>
      
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td><%= user.email %></td>
              <td><%= link_to 'Show', user %></td>
              <td><%= link_to 'Edit', edit_user_path(user) %></td>
              <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      
      <br>


    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      

      <!-- マイページ -->
      <p id="notice"><%= notice %></p>
      
      <div class="col-sm-4">
      <div class="my_right">
        
        <div class="my_image">
          <strong>image:</strong>
          <% if @user.image %>
            <%= image_tag "/user_images/#{@user.image}" %>
          <% else %>
            <%= image_tag "image.png" %>
          <% end %>
        </div>
        
        <div class="">
          <strong>Name:</strong>
          <%= @user.name %>
        </div>
        
        <div class="">
          <strong>StudentType:</strong>
          <% if @user.studentType == "その他" %>
          <%= @user.studentType %>
          <% else %>
          <%= @user.studentType %>   <!-- 小学生なら学年を表示 -->
          <%= @user.studentYear %>年生
          <% end %>
        </div>
        
        <div class="">
          <strong>Email:</strong>
          <%= @user.email %>
        </div>
  
        <div class="">
          <% if user_signed_in? && current_user.id == @user.id %>
          <%= link_to 'へんしゅう', edit_user_path(@user) %>
          <% end %>
        </div>
        
      </div>
      </div> 
      
      <div class="col-sm-8">
      <div class="my_left">  
        
        <!-- いいねしたコメント -->
        <div class="like">いいねしたコメント
          <div class="">
            <% @notes.each do |note| %>
            <div class="">
              <%= note.user.name %>
              <%= note.user.studentType %>
              <% if note.user.studentType != "その他" %>
              <%= note.user.studentYear %>
              <% end %>
              <%= note.content %>
              <% if user_signed_in? && current_user.id == @user.id %>
                <div id="like-link-<%= note.id %>" style="margin-bottom: 0.5rem;"><!-- like-linkはAjaxで使うから残しといて タグ名は変えていいよ(div→spanとか) -->
                  <%= render "likes/like_links", note: note %>
                </div>
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
        
        <!-- お気に入りのチャットルーム -->
        <div class="favorite">お気に入りのチャットルーム
          <div class="">
            <% @chatrooms.each do |chatroom| %>
            <div class="">
              <div class="btn-group">
                <% subject_class = {'国語'=>'btn btn-danger btn-xs', '算数'=>'btn btn-info btn-xs', '理科'=>'btn btn-success btn-xs', '社会'=>'btn btn-warning btn-xs'} %>
                <% year_class = { 3=>'btn btn-xs btn-primary', 4=>'btn btn-xs btn-warning', 5=>'btn btn-xs btn-info', 6=>'btn btn-xs btn-success' } %>
                <%= button_tag chatroom.subject, :name => 'subject', :class => subject_class[chatroom.subject], :type => 'submit', :disabled => 'disable' %>
                <%= button_tag chatroom.studentYear.to_s + '年', :name => 'studentyear', :class => year_class[chatroom.studentYear], :type => 'submit', :disabled => 'disable' %>
                <%= link_to chatroom.title, chatroom, :class => 'btn btn-default btn-xs' %>
              </div>
              <% if user_signed_in? && current_user.id == @user.id %>
                <div id="favorite-link" style="margin-bottom: 0.5rem;"> <!-- favorite-linkはAjaxで使うから残しといて タグ名は変えていいよ(div→spanとか) -->
                  <%= render "favorites/favorite_links", chatroom: chatroom %>
                </div>
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
        
        <!-- 友達申請 -->
        <div class="friend">
          <% if user_signed_in? && current_user.id != @user.id && @user.id != 17 %>
            <%= link_to '友達しんせいする', submit_path(@user.id), :method => :post %>
          <% end %>
          
        </div>
        <div class="">
          <% if @user.id == 3 %><!-- ゆきさんのみ -->
          <div class="">
            友達
              <div class="">
                <%= link_to 'aki', user_path(5) %>
                <%= link_to 'チャットルームに行く', chatroom_path(11) %>
              </div>
          </div>
          <div class="friendship">
            <%= link_to 'かな', user_path(16) %>さんから友達しんせいが届いています
          </div>
          <% end %>
          <% if @user.id == 5 %><!-- akiさんのみ -->
          <div class="">
            友達
              <div class="">
                <%= link_to 'ゆき', user_path(3) %>
                <%= link_to 'チャットルームに行く', chatroom_path(11) %>
              </div>
          </div>
          <% end %>
        </div>
        
      </div>  
      </div>
      
    </div>
  </div>
</div>