config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
  }
  resources :chatrooms
  resources :users
  resources :notes
  root 'home#top'
  post '/' => 'home#mystudentyear'
  get '/about' => 'home#about'
  get '/mytop' => 'home#mytop'
  post '/mytop'=> 'home#mysubject'
  post '/like/:note_id' => 'likes#like', as:'like'
  delete '/unlike/:note_id' => 'likes#unlike', as:'unlike'
  post '/favorite/:chatroom_id' => 'favorites#favorite', as:'favorite'
  delete '/unfavorite/:chatroom_id' => 'favorites#unfavorite', as:'unfavorite'
  post '/friendship/:user_id' => 'friendships#submit', as:'submit'
  
  

end

app/models/chatroom.rb
class Chatroom < ActiveRecord::Base
    has_many :notes
    has_many :favorites, dependent: :destroy
    validates :title, presence: true
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
    belongs_to :user
    belongs_to :chatroom
end

app/models/friend.rb
class Friend < ActiveRecord::Base
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
    belongs_to :from_user, class_name: 'User', foreign_key: 'from_user_id'
    belongs_to :to_user, class_name: 'User', foreign_key: 'to_user_id'
end

app/models/like.rb
class Like < ActiveRecord::Base
    belongs_to :user
    belongs_to :note
end

app/models/note.rb
class Note < ActiveRecord::Base
    belongs_to :user
    belongs_to :chatroom
    has_many :likes, dependent: :destroy
    validates :content, presence: true
    validates :user_id, presence: true
end

app/models/prv_chatroom.rb
class PrvChatroom < ActiveRecord::Base
end

app/models/prv_note.rb
class PrvNote < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_many :notes
    has_many :likes, dependent: :destroy
    has_many :like_notes, through: :likes, source: :note
    has_many :favorites, dependent: :destroy
    has_many :favorite_chatrooms, through: :favorites, source: :chatroom
    has_many :friendships_from_user, class_name: 'Friensdhip', foreign_key: 'from_user_id', dependent: :delete_all
    has_many :friendships_to_user, class_name: 'Friedship', foreign_key: 'to_user_id', dependent: :delete_all
    has_many :friendships_of_from_user, through: :friendships_from_userr, source: 'to_user'
    has_many :friendships_of_to_user, through: :friendships_to_user, source: 'from_user'
    validates :name, presence: true 
    validates :email, presence: true, uniqueness: true
    validates :studentType, presence: true
    
    
    def set_image(file)
        if !file.nil?
            file_name = file.original_filename

            File.open("public/user_images/#{file_name}", 'wb'){|f| f.write(file.read)}
        end
        
        self.image = file_name

    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def top
    if user_signed_in? && !(current_user.studentType == "その他")
      $studentyear = current_user.studentYear
      redirect_to mytop_path
    end
    @chatrooms = Chatroom.order(:updated_at)
  end
  
  def about
  end
  
  def mytop
    unless defined? $studentyear
      redirect_to root_path
    end
    @chatrooms = Chatroom.order("updated_at")
  end
  
  def mystudentyear
    #topページ下部のボタンからのリンク接続
    if params[:studentyear].present? then
      $studentyear = params[:studentyear].to_i
      redirect_to mytop_path
    elsif params[:subject].present? then
      subyear = params[:subject].partition(/[3-6]/)
      $subject = subyear[0]
      $studentyear = subyear[1].to_i
      redirect_to chatrooms_path
    elsif params[:chatroom].present? then
      subyearid = params[:chatroom].partition(/[3-6]/)
      $subject = subyearid[0]
      $studentyear = subyearid[1].to_i
      redirect_to chatroom_path(subyearid[2].to_i)
    end
      
  end
  
  def mysubject
    #topページ下部のボタンからのリンク接続
    if params[:subject].present? then
      $subject = params[:subject]
      redirect_to chatrooms_path
    elsif params[:chatroom].present? then
      subyearid = params[:chatroom].partition(/[0-9]*$/)
      $subject = subyearid[0]
      redirect_to chatroom_path(subyearid[1].to_i)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/prvnotes_helper.rb
module PrvnotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StudyBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <meta charset="utf-8">
  
</head>
<body>
  <header class="navbar navbar-default" style="margin-bottom: 0;">
    <div class="headerLeft navbar-header">
      <%= link_to "スタディ ボード", root_path %>
    </div>
    <button class="navbar-toggle" data-toggle="collapse" data-target=".target">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div class="headerRight collapse navbar-collapse target">
    <% if user_signed_in? %>
      <ul class="headerRightTitle">
        <li><%= link_to "トップ", root_path %></li>
        <li><%= link_to "マイページ", user_path(current_user.id) %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
      </ul>
    <% else %>
      <ul class="headerRightTitle">
        <li><%= link_to "トップ", root_path %></li>
        <li><%= link_to "ログイン", new_user_session_path %></li>
        <li><%= link_to "とうろく", new_user_registration_path %></li>
      </ul>
    <% end %>
    </div>
  </header>
  <div class="contents">
  <%= yield %>
  </div>
  <div id="top-link-bot"><a href=""><%= image_tag("arrow.png", :size => "35x35", :alt => "アイコン", :style => "position: fixed; right: 3%; bottom: 5%;") %></a></div>
</body>
</html>

<!--
    <div class="headerLeft">
      <%= link_to "スタディ ボード", root_path %>
    </div>
    <div class="headerRight">
    <% if user_signed_in? %>
      <ul class="headerRightTitle">
        <li><%= link_to "トップ", root_path %></li>
        <li><%= link_to "マイページ", user_path(current_user.id) %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
      </ul>
    <% else %>
      <ul class="headerRightTitle">
        <li><%= link_to "トップ", root_path %></li>
        <li><%= link_to "ログイン", new_user_session_path %></li>
        <li><%= link_to "とうろく", new_user_registration_path %></li>
      </ul>
    <% end %>
    </div>


-->